version: '3.10'
services:
  postgres_db:
    container_name: ma_test_postgres
    image: postgres:16.0-alpine
    volumes:
      - ma_test_postgres_data:/var/lib/postgresql/ma_test_postgres_data/
    environment:
      - POSTGRES_DB=ma_test
      - POSTGRES_USER=ma_test
      - POSTGRES_PASSWORD=ma_test
    ports:
      - "5434:5432"
volumes:
  ma_test_postgres_data: