"""Changed relationship

Revision ID: fa9c3288f6f2
Revises: 8c6b5b5f3a8d
Create Date: 2024-08-28 03:35:38.289618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa9c3288f6f2'
down_revision: Union[str, None] = '8c6b5b5f3a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
